stages:
  - spec

spec:
  stage: spec
  image: jreinert/crystal-alpine:latest
  before_script:
    - apk add gpgme-dev
    - shards install
  variables:
    POPULATE_KEYRING: 'true'
  script:
    - crystal spec -Dmusl
