sudo: required

services:
  - docker

before_install:
  - docker build --tag crystal .
  - docker run -v $PWD:/project -w /project crystal shards install

script:
  - docker run -v $PWD:/project -w /project -e POPULATE_KEYRING=1 crystal crystal spec
